# Site settings
title: "Reversing.AC - The way to stay under radars"
bye_message: "~"
baseurl: "/"
url: "https://cpz.github.io/"
disqus: 0og

# Header settings
nick: "cpz"
mail:
    domain: "reversing"
    ext: "ac"
source_code:
    server: "github.com"
    nick: "cpz"
twitter:
    server: "twitter.com"
    nick: "dg_cpz"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
