# Site settings
title: "Reversing.AC"
bye_message: "~"
baseurl: "https://cpz.github.io"
url: "https://cpz.github.io"
disqus: 0og

# Header settings
nick: "cpz"
mail:
    domain: "protonmail"
    ext: "ch"
source_code:
    server: "github.com"
    nick: "cpz"
blog:
    server: ""
    nick: ""
fingerprint_key: ""

# Build settings
markdown: kramdown
permalink: /:categories/:title/
